version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/harex89-lsy05dqln16k
  api_key:
    secure: rgq0lss9d46q8svr06fnpo15
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: rgq0lss9d46q8svr06fnpo15
  on:
    branch: master
    appveyor_repo_tag: true